server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
#  server:
#    #关闭自我保护
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
  client:
    #false 表示不向注册中心注册自己
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（互相组注册）
      defaultZone: http://eureka7002.com:7002/eureka/

