server:
  port: 8082

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb?useUnicode=true&charsetEncoding=utf8
    username: root
    password: 1314qawsed
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: payment8082  #Eureka面板信息修改
    prefer-ip-address: true #访问路径可以显示IP地址
  client:
    register-with-eureka: true
    fetchregistry: true
    serviceUrl:
      #单机版
#      defaultZone: http://localhost:7001/eureka/
      #集成版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/



