server:
  port: 8082

spring:
  application:
    name: cloud-provider-service
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb?useUnicode=true&charsetEncoding=utf8
    username: root
    password: 1314qawsed
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetchregistry: true
    serviceUrl:
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka



