server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb?useUnicode=true&charsetEncoding=utf8
    username: root
    password: 1314qawsed
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    zookeeper:
      connect-string: 192.168.200.128